### ISSUE TITLE
connection

### ISSUE THREAD

**Issue by BearsieIsNice** [MonsterDruide1/smo-practice-server#3]
The documentation doesn't say how to connect to the mod.

**Comment by MonsterDruide1** [comment]
Sorry, didn't notice your message here...

First up, you don't connect the server to the mod, but the mod to the server - the connection has to be initiated by the mod, which can be done on the TASing page by pressing D-RIGHT on `Connect to Server`. In most cases, you'll need a custom-built version of the mod, tailored for the IP of the device you want to run the server on. You can either build that yourself, or ask someone in the community to build the mod for you.

I'd gladly help you with the process over in the SMO-TAS Discord, it's a bit easier there than using the GitHub issues.
https://discord.gg/atKSg9fygq

If you don't have Discord or prefer to continue the conversation here for any other reason, feel free to re-open this issue,
